server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://customers-db:5432/customers}
    username: ${DB_USER:customers}
    password: ${DB_PASSWORD:customers}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
