server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://accounts-db:5432/accounts}
    username: ${DB_USER:accounts}
    password: ${DB_PASSWORD:accounts}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

customers:

